// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WindowsPerfGUI
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string WindowsPerfGUIString = "496c2178-b18c-47e3-b4b3-586827fe382b";
        public static Guid WindowsPerfGUI = new Guid(WindowsPerfGUIString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommand = 0x0100;
        public const int WperfHostData = 0x0101;
        public const int SamplingExplorer = 0x0102;
        public const int CountingSettings = 0x0103;
        public const int WperfMan = 0x0104;
    }
}