// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Windows_Perf_GUI
{
    internal sealed partial class Vsix
    {
        public const string Id = "Windows_Perf_GUI.73de2c45-cf60-4edb-a092-b09b43acf2ae";
        public const string Name = "Windows_Perf_GUI";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "0.0.1";
        public const string Author = "Nader Zouaoui";
        public const string Tags = "";
    }
}
